version: '3'

services:
  zabbix-db:
    image: mysql:5.7
    container_name: zabbix-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - ./zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.0
    container_name: zabbix-server
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    volumes:
      - ./zabbix-server-data:/var/lib/zabbix
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.0
    container_name: zabbix-frontend
    ports:
      - "8080:8080"
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Riga
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: zabbix-db
      PMA_PORT: 3306
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  grafana-data:
